apiVersion: v1
stringData:
  localMinIO: |
    {
      "type": "s3",
      "access_key_id": "minio",
      "secret_access_key": "minio123",
      "endpoint_url": "http://minio-service.kubeflow.svc.cluster.local:9000",
      "bucket": "mlpipeline",
      "region": "us-east",
      "anonymous": "False"
    }
kind: Secret
metadata:
  name: storage-config
type: Opaque