apiVersion: v1
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
kind: Secret
metadata:
  annotations:
    serving.kserve.io/s3-endpoint: minio-service.kubeflow.svc.cluster.local:9000
    serving.kserve.io/s3-useanoncredential: "false"
    serving.kserve.io/s3-usehttps: "0"
  name: minio-secret
  namespace: dev-profile
type: Opaque
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-sa
  namespace: dev-profile
secrets:
  - name: minio-secret