apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "failure-rate-transformer"
  namespace: "dev-profile"
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  transformer:
    containers:
    - image: upscale-docker.docker.repositories.cloud.sap/upscale-sre-docker/kubeflow-poc/kubeflow-poc-transformer-component:0.01
      name: transformer-container
      command:
      - "python"
      - "-m"
      - "failure_rate_transformer"
    imagePullSecrets:
    - name: "artifactory-auth"
  predictor:
    serviceAccountName: minio-sa
    sklearn:
      args: 
        - --model_dir=/mnt/models/data
      storageUri: "s3://mlpipeline/artifacts/failure-rate-pipeline-dknpz/2022/02/28/failure-rate-pipeline-dknpz-1803733580/train-model-function-Data.tgz"